[package]
name = "soul"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
needletail = "0.5"
rayon = "1.10"
dashmap = "6.0"
anyhow = "1.0"
itertools = "0.13"